name: Code checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r lab14/requirements.txt
      - name: Run tests
        run: |
          python lab14/test.py
